import { timestamp, uuid } from "drizzle-orm/pg-core";

/** UUID primary key generated by Postgres (gen_random_uuid). */
export const id = () => uuid("id").primaryKey().defaultRandom();

export const timestamptz = (name: string) => timestamp(name, { withTimezone: true, mode: "date" });

/** created_at / updated_at on every table (PROJECT_SPEC §9). */
export const timestamps = {
  createdAt: timestamptz("created_at").notNull().defaultNow(),
  updatedAt: timestamptz("updated_at")
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date()),
};
